kind: Pod
apiVersion: v1
metadata:
  name: roo-app
  labels:
    app: roo
spec:
  containers:
  - name: roo-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=roo"
---
kind: Service
apiVersion: v1
metadata:
  name: roo-service
spec:
  selector:
    app: roo
  ports:
  # Default port used by the image
  - port: 5678
---
kind: Pod
apiVersion: v1
metadata:
  name: barr-app
  labels:
    app: barr
spec:
  containers:
  - name: barr-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=barr"
---
kind: Service
apiVersion: v1
metadata:
  name: barr-service
spec:
  selector:
    app: barr
  ports:
  # Default port used by the image
  - port: 5678
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - path: /roo
        backend:
          serviceName: roo-service
          servicePort: 5678
      - path: /barr
        backend:
          serviceName: barr-service
          servicePort: 5678
---

